### ISSUE TITLE
Warpcore Status

### ISSUE THREAD

**Issue by atom-moyer** [sleeepyjack/warpcore#7]
Hello,

I came across this repo, and would like to get caught up to date with the status.

Is this still considered the best hashmap/dictionary for GPU accelerate applications?

Has someone generated bindings for the package that interfaces it with deep learning packages in python?

Is there expected to be support on the A100/H100 architectures?

Thanks,
Adam

**Comment by sleeepyjack** [comment]
Hi Adam,
Thanks for reaching out.

Unfortunately, this project is no longer actively maintained.
Most concepts introduced by WarpCore have been merged into the OSS library [NVIDIA/cuCollections](https://github.com/NVIDIA/cuCollections), which is actively maintained (I am one of the maintainers), production-grade (used in e.g. RAPIDS), and provides even better performance than WarpCore.
If you want to use it for research, you can still cite WarpCore due to the implementation overlap with cuCollection.

>Has someone generated bindings for the package that interfaces it with deep learning packages in python?

I am not aware of any existing Python bindings for both WarpCore and cuCollections.

>Is there expected to be support on the A100/H100 architectures?

cuCollections is optimized for both A100 and H100.

Regards,
Daniel
